### ISSUE TITLE
Example doesn't seem to work

### ISSUE THREAD

**Issue by hardbyte** [hipagesgroup/hyperkops#15]
I deployed with default values via the helm chart at https://github.com/hipagesgroup/chart-hyperopt and the workers fail to start with "Back-off restarting failed container" due to the following exception caused by the example workload:

```
 INFO:hyperopt.mongoexp:job exception: name 'log' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/hyperopt-mongo-worker", line 10, in &lt;module&gt;
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1267, in main
    sys.exit(main_worker())
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1317, in main_worker
    return main_worker_helper(options, args)
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1261, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/usr/local/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1085, in run_one
    result = worker_fn(spec, ctrl)
  File "/usr/local/lib/python3.6/site-packages/hyperopt/base.py", line 844, in evaluate
    rval = self.fn(pyll_rval)
  File "/usr/local/hyperkops_example/optimisation.py", line 107, in objective_curried
NameError: name 'log' is not defined 
```

**Comment by datascienceChris** [comment]
Hi, thanks for the feedback. We've updated the example, and it should work now. Let us know how you get on.

As it stands the workers fail when they haven't had picked up any jobs after certain amount of time as it stands we just let them restart as part of the deployment, but its something we should put onto the backlog.

**Comment by datascienceChris** [comment]
Just waiting to test the updated chart with the new images.

**Comment by datascienceChris** [comment]
Chart is now fixed, and I've bug fixed some issues in the initial release. Let us know hwo you get on.
